---
- name: copy and unarchive redis-{{redis_version}}.tar.gz
  unarchive:
    src: redis-{{redis_version}}.tar.gz
    dest: /App/src

- name: move to /usr/local/redis
  command: mv /App/src/redis-{{redis_version}} /usr/local/redis

- name: make
  make:
    chdir: /usr/local/redis

- name: edit /etc/profile
  blockinfile:
    path: /etc/profile
    marker: "# {mark} ANSIBLE MANAGED BLOCK: redis"
    block: export PATH=/usr/local/redis/src:$PATH

- name: link /etc/redis.conf
  file:
    src: /usr/local/redis/redis.conf
    dest: /etc/redis.conf
    state: link

- name: edit /etc/redis.conf
  lineinfile:
    path: /etc/redis.conf
    regexp: "^bind " 
    line: "bind 0.0.0.0"

- name: edit /etc/redis.conf
  lineinfile:
    path: /etc/redis.conf
    regexp: "^daemonize " 
    line: "daemonize yes"

- name: edit /etc/redis.conf
  lineinfile:
    path: /etc/redis.conf
    regexp: "^dir" 
    line: "dir /data/redis"

- name: generate random password
  shell: openssl rand 32 -base64 | head -c 16
  register: random_password

- name: edit /etc/redis.conf
  lineinfile:
    path: /etc/redis.conf
    regexp: "requirepass" 
    line: "requirepass {{ random_password.stdout }}"

- name: make directory /data/redis
  file:
    path: /data/redis
    state: directory

- name: edit /etc/rc.local
  blockinfile:
    path: /etc/rc.local
    marker: "# {mark} ANSIBLE MANAGED BLOCK: redis"
    block: "/usr/local/redis/src/redis-server /etc/redis.conf"

- name: start redis
  command: /usr/local/redis/src/redis-server /etc/redis.conf

- name: "print password !!!"
  debug:
    msg: "redis password : {{ random_password.stdout }}"
