---
- include_vars: /etc/ansible/vars/main.yml

- name: install pip
  yum:
    name: python-pip
    state: present

- name: install pymongo
  pip:
    name: pymongo
    extra_args: --proxy http://{{proxy_hostname}}:{{proxy_port}}

- name: change mode of /data/sa
  file:
    path: /data/sa
    state: directory
    mode: 0755

- name: copy /App/script/zabbix-sa.sh
  copy:
    src: zabbix-sa.sh
    dest: /App/script/zabbix-sa.sh
    mode: 0755

- name: copy /App/script/zabbix-sa.py
  template:
    src: zabbix-sa.py.j2
    dest: /App/script/zabbix-sa.py
    mode: 0755

- name: add crontab zabbix-sa
  cron:
    backup: yes
    name: zabbix-sa
    user: sa
    job: /App/script/zabbix-sa.sh >> /tmp/zabbix-sa.log 2>&1
