---
- name: copy /etc/zabbix_agentd.conf.d/userparameter_diskstats.conf
  copy:
    src: userparameter_diskstats.conf
    dest: /etc/zabbix_agentd.conf.d/
  notify:
    - zabbix_agentd restart

- name: copy /usr/local/bin/lld-disks.py
  copy:
    src: lld-disks.py
    dest: /usr/local/bin/
    mode: 775
  notify:
    - zabbix_agentd restart
