- name: create /Apy/src
  file:
    path: /App/src
    state: directory

- name: create /App/script
  file:
    path: /App/script
    state: directory

- name: create /data
  file:
    path: /data
    state: directory

- name: install vim
  yum:
    name: vim
    state: latest

- name: install libselinux-python
  yum:
    name: libselinux-python
    state: latest

- name: disabled SELinux
  selinux:
    state: disabled

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- include: patch-local.yml
  when: ansible_env.SSH_CLIENT | search("192.168.25.165")
