- name: create /Apy/src
  file:
    path: /App/src
    state: directory

- name: create /App/script
  file:
    path: /App/script
    state: directory

- name: create /data
  file:
    path: /data
    state: directory

- name: install vim
  yum:
    name: vim
    state: latest

- name: install libselinux-python
  yum:
    name: libselinux-python
    state: latest

- name: install ntpdate
  yum:
    name: ntpdate
    state: latest

- name: set DNS
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf

- name: disabled SELinux
  selinux:
    state: disabled

- name: sync time
  shell: /usr/sbin/ntpdate cn.pool.ntp.org && hwclock --systohc

- name: add crontab(sync time)
  cron:
    backup: yes
    minute: 0
    hour: 3
    name: sync time
    job: /usr/sbin/ntpdate cn.pool.ntp.org && hwclock --systohc

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
