---
- name: add user zabbix
  user:
    name: zabbix

- name: copy /etc/zabbix_agentd.conf (local)
  copy:
    src: zabbix_agentd.conf.local
    dest: /etc/zabbix_agentd.conf
  when:
    ansible_env.SSH_CLIENT | search("192.168.25.165")
  notify:
    - zabbix_agentd restart

- name: copy /etc/zabbix_agentd.conf (aliyun)
  copy:
    src: zabbix_agentd.conf.aliyun
    dest: /etc/zabbix_agentd.conf
  when:
    ansible_env.SSH_CLIENT | search("192.168.25.165")
  notify:
    - zabbix_agentd restart

- name: copy /etc/zabbix_agentd.conf (jushita)
  copy:
    src: zabbix_agentd.conf.local.jushita
    dest: /etc/zabbix_agentd.conf
  when:
    ansible_env.SSH_CLIENT | search("10.26.114.77")
  notify:
    - zabbix_agentd restart

- name: copy /usr/local/sbin/zabbix_agentd
  copy:
    src: zabbix_agentd.bin
    dest: /usr/local/sbin/zabbix_agentd
    mode: 0755
  notify:
    - zabbix_agentd restart

- name: copy /etc/init.d/zabbix_agentd
  copy:
    src: zabbix_agentd.init
    dest: /etc/init.d/zabbix_agentd
    mode: 0755
  notify:
    - zabbix_agentd restart

- name: enable serveice zabbix_agentd
  service:
    name: zabbix_agentd
    enabled: yes
